### ISSUE TITLE
Property 'historyPush' does not exist on type 'cy & EventEmitter'.ts(2339)

### ISSUE THREAD

**Issue by TheDiveO** [mauricedb/cypress-react-router#15]
Hi Maurice,

I've added your package to my project using `yarn add --dev cypress-react-router`. I've also added the necessary `import 'cypress-react-router/add-commands'` to my `cypress/support/index.ts`.

Now, in some end-to-end integration test `cypress/integration/endtoend.spec.ts` VScode now complains when I try to use `cy.historyPush` with:

    Property 'historyPush' does not exist on type 'cy & EventEmitter'.ts(2339)

Albeit your package contains an `dist/addReactRouterHistoryCommand.d.ts` it doesn't seem to get picked up by VScode. The test run fine, so this just VScode not finding your typescript definitions.

These are my tsconfig.jsons, first `cypress/tsconfig.json`:

```json
{
    "extends": "../tsconfig.json",
    "compilerOptions": {
        "target": "es5",
        "lib": [
            "es5",
            "dom"
        ],
        "types": [
            "node",
            "cypress",
            "cypress-react-selector"
        ]
    },
    "include": [
        "**/*.ts",
        "**/*.tsx"
    ]
}
```

...and then my main `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "downlevelIteration": true,
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "noEmit": true,
    "baseUrl": "src",
    "noFallthroughCasesInSwitch": false,
    "types": [
      "cypress",
      "cypress-react-selector",
      "cypress-react-router"
    ]
  },
  "include": [
    "src",
    "styleguidist"
  ]
}
```

What I'm missing or configuring wrong?

PS: adding "cypress-react-router" to the `types` element in my main `tsconfig.json` and restarting either the TS language server or VScode didn't help either.

**Comment by mauricedb** [comment]
The type definition is [here](https://github.com/mauricedb/cypress-react-router/blob/main/src/addReactRouterHistoryCommand.ts#L6) but it seems it isn't picked up. I need to take a look at why and see how to fix this. As a workaround the following should work:

```
import { Path, LocationState } from 'history';

declare namespace Cypress {
  interface Chainable<Subject = any> {
    historyPush(path: Path, state?: LocationState): Chainable<Subject>;
    historyReplace(path: Path, state?: LocationState): Chainable<Subject>;
  }
}
```

**Comment by mauricedb** [comment]
Just tried and for me everything works as expected. See the commit where I configured and use `cypress-react-router` [here](https://github.com/mauricedb/cypress-react-router-demo-2021-02-14/commit/067173423b9d5176f5b2bc7fcd33115a66a8499f).

The only thing I noticed in your `tsconfig.json` is you added `cypress-react-router` in the base `tsconfig` to the `types` but in the `tsconfig.json` in the `cypress` folder you overrule the `types` and `cypress-react-router` is not included.

**Comment by TheDiveO** [comment]
Thank you very much for taking the time to spot my mistake! Yes, of course, the `cypress-react-router` type was missing and after adding it, things now work as expected. I didn't notice that it was affecting only the end-to-end integration specifications. Another example of not seeing the wood for the trees.
